# Windstille - A Sci-Fi Action-Adventure Game
# Copyright (C) 2018 Ingo Ruhnke <grumbel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

image: ubuntu:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get -qq update
  - apt-get -qq -y install lsb-release
  - lsb_release -a
  - apt-get -qq -y install
    clang-6.0
    g++-8
    cmake
    build-essential
    software-properties-common
    desktop-file-utils
    appstream-util
    libc++-dev
    libboost-dev
    libboost-filesystem-dev
    libboost-system-dev
    libboost-signals-dev
    libsdl2-dev
    libsdl2-image-dev
    libsdl2-mixer-dev
    libpng-dev
    flex
    bison
    libcurl4-gnutls-dev
    libfreetype6-dev
    libglew-dev
    libglm-dev
    libgtkglextmm-x11-1.2-dev
    libgtkmm-2.4-dev
    libmagick++-dev
    libogg-dev
    libopenal-dev
    libphysfs-dev
    libvorbis-dev
    xcftools

.build_windstille_template: &build_windstille
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS=ON -DWERROR=ON -DBUILD_TESTS=ON -DBUILD_EXTRA=ON
    - make VERBOSE=1
    - make test VERBOSE=1 ARGS="-V"

build:gcc:release:
  <<: *build_windstille
  variables:
    CXX: g++-8
    BUILD_TYPE: Release

build:clang:release:
  <<: *build_windstille
  variables:
    CXX: clang++-6.0
    BUILD_TYPE: Release

build:gcc:debug:
  <<: *build_windstille
  variables:
    CXX: g++-8
    BUILD_TYPE: Debug

build:clang:debug:
  <<: *build_windstille
  variables:
    CXX: clang++-6.0
    BUILD_TYPE: Debug

build:flatpak:
  stage: build
  script:
    - add-apt-repository -y ppa:alexlarsson/flatpak
    - apt-get -qq update
    - apt-get -qq -y install flatpak flatpak-builder
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak install -y flathub org.freedesktop.Platform org.freedesktop.Sdk
    - flatpak-builder --repo=build-flatpak-repo/ build-flatpak/ io.gitlab.windstille.Windstille.json
    - flatpak build-bundle build-flatpak-repo/ windstille.flatpak io.gitlab.windstille.Windstille
  artifacts:
    paths:
      - windstille.flatpak
      - build-flatpak-repo

# pages:
#   stage: deploy
#   dependencies:
#     - build:flatpak
#   script:
#     - mkdir public.tmp/
#     - mv -v build-flatpak-repo public.tmp/flatpakrepo
#     - mv -v public.tmp public
#   artifacts:
#     paths:
#     - public

# EOF #
