/**
 * WARNING: This file is automatically generated from:
 *  'src/scripting/wrapper.interface.hpp'
 * DO NOT CHANGE
 */
#ifndef __windstille_WRAPPER_H__
#define __windstille_WRAPPER_H__

#include <squirrel/squirrel.h>

namespace Scripting
{

void register_windstille_wrapper(HSQUIRRELVM v);

class GameObject;
void create_squirrel_instance(HSQUIRRELVM v, Scripting::GameObject* object, bool setup_releasehook = false);
class TestObject;
void create_squirrel_instance(HSQUIRRELVM v, Scripting::TestObject* object, bool setup_releasehook = false);
class Player;
void create_squirrel_instance(HSQUIRRELVM v, Scripting::Player* object, bool setup_releasehook = false);
class ScriptableObject;
void create_squirrel_instance(HSQUIRRELVM v, Scripting::ScriptableObject* object, bool setup_releasehook = false);

}

#endif
