## -*- python -*-

import glob

env = Environment(CPPPATH = ['include'])

env.Library('squirrel',
            glob.glob('squirrel/*.cpp') +
            glob.glob('sqstdlib/*.cpp')  +
            glob.glob('sqstdlib/*.c'))


# EOF #
